#pragma once

#define PLOOPY_DRAGSCROLL_MOMENTARY
#define PLOOPY_DRAGSCROLL_DIVISOR_H 64.0
#define PLOOPY_DRAGSCROLL_DIVISOR_V 64.0
#define PLOOPY_DRAGSCROLL_INVERT

#define PLOOPY_DRAGSCROLL_THRESHOLD_H 1
#define PLOOPY_DRAGSCROLL_THRESHOLD_V 0
